### ISSUE TITLE
mix creation with same name possible

### ISSUE THREAD

**Issue by stopcap** [JOJ0/discodos#4]
Test Env: Windows 7

2 x 

> disco mix -c "mix1"

possible.

Hence adding tracks to 2nd mix with the name "mix1" not possible!

Intended?

**Comment by JOJ0** [comment]
hi,
creating two mixes with the same name is not forbidden - maybe it should be....thinking about that.

it's still possible to access both of them:

`disco mix`

shows the mixes IDs. so to access them you could just use those IDs:
```
disco mix 1 --something
disco mix 2 --something
```

hope that helps
Jojo

**Comment by JOJ0** [comment]
Creation of duplicate mix-names is now forbidden, and also taken care of in mix-edit (mix -E)

c6a7303d76d218533a0e11ad9c4249123b114e2b
f4b2a88788131f8bbbb9ed045cdb80c464140884

Thanks for reporting!
